#!/bin/bash

rsync -avP * db12:gen_v_sharp/ --exclude='*/checkpoints/' --exclude='*/data/' \
	--exclude='*/results/' --exclude="sync"

rsync -avP * db7:gen_v_sharp/ --exclude='*/checkpoints/' --exclude='*/data/' \
	--exclude='*/results/' --exclude="sync"

rsync -avP * db2:gen_v_sharp/ --exclude='*/checkpoints/' --exclude='*/data/' \
	--exclude='*/results/' --exclude="sync"
