#!/bin/bash

query_device() {
	for d in 0 1 2 3
	do
		dmem="$(nvidia-smi -q -i ${d} -d Memory |grep -A4 GPU | grep Used | grep -Eo '[0-9]{1,5}')"
		if (($dmem < 50)); then
		    device=${d}
		fi
	done
}

get_device() {
	unset device
	while [[ -z "${device}" ]]
	do
		query_device
		if [[ -z "${device}" ]]; then
			echo "All devices are busy, sleeping for 60s"
			sleep 60
		fi
	done
}

for exp_num in {0..1300}; do
	get_device
	CUDA_VISIBLE_DEVICES=$((device)) nohup python train.py \
		--dtype="cifar10" \
		--print_freq=100 \
		--exp_num=${exp_num} 2>&1 &
	sleep 30
done
