#!/bin/bash

query_device() {
	for d in 0 1 2 3
	do
		dmem="$(nvidia-smi -q -i ${d} -d Memory |grep -A4 GPU | grep Used | grep -Eo '[0-9]{1,5}')"
		if (($dmem < 10)); then
		    device=${d}
		fi
	done
}

get_device() {
	unset device
	while [[ -z "${device}" ]]
	do
		query_device
		if [[ -z "${device}" ]]; then
			echo "All devices are busy, sleeping for 10s"
			sleep 10
		fi
	done
}

for exp_num in {60..80}; do
	get_device
	CUDA_VISIBLE_DEVICES=$((device)) nohup python invest_dl_prob.py \
		--exp_num=${exp_num} --dtype="mnist" > jobs/${exp_num}.out 2>&1 &
	sleep 5
	# CUDA_VISIBLE_DEVICES=$((device)) nohup python train.py \
	# 	--ep=500 \
	# 	--dtype="mnist" \
	# 	--print_freq=500 \
	# 	--exp_num=${exp_num} >/dev/null 2>&1 &
	# sleep 30
done
