#!/bin/bash

query_device() {
	for d in 0 1 2 3
	do
		dmem="$(nvidia-smi -q -i ${d} -d Memory | grep -A4 GPU | grep Used | grep -Eo '[0-9]{1,5}')"
		if (($dmem < 50)); then
		    device=${d}
		fi
	done
}

get_device() {
	unset device
	while [[ -z "${device}" ]]
	do
		query_device
		if [[ -z "${device}" ]]; then
			echo "All devices are busy sleeping for 60s"
			sleep 60
		fi
	done
}

for bs in 128 1024
do
	for lr in 0.1
	do
		for m in 0.9 0.99 0.995
		do
			get_device
			CUDA_VISIBLE_DEVICES=$((device)) nohup python train.py \
				-lr=${lr}  \
				-wd=0.0  \
				-m=${m}  \
				--bs=${bs}  \
				--dtype="mnist"  \
				--print_freq=50  \
				--ep=200 \
				-opt="amsgd" &
			sleep 30
		done
	done
done
